gallery_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='index'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('accounts/register', views.register, name='register'),
    path('logout/', views.custom_logout, name='logout'),
    path('profile', views.profile_view, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('upload/', views.photo_upload, name='photo_upload'),
    path('like/<int:photo_id>/', views.like_photo, name='like_photo'),
    path('dislike/<int:photo_id>/', views.dislike_photo, name='dislike_photo'),
    path('photo/<int:photo_id>/', views.photo_detail, name='photo_detail'),

]

photo_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gallery_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]
urlpatterns += staticfiles_urlpatterns()

gallery_app/models.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=1)
    bio = models.TextField()
    profile_picture =CloudinaryField("image", null=True)
    
    def __str__(self):
            return self.user.username

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class Photo(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    tags = models.ManyToManyField(Tag, related_name="photos", blank=True)
    uploaded_photo =CloudinaryField("image", null=True)
    total_likes = models.PositiveIntegerField(default=0)
    total_dislikes = models.PositiveIntegerField(default=0)    
    
    def __str__(self):
            return self.title

class Subscriber(models.Model):
    email = models.EmailField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

# Create your models here.

gallery_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Photo, Tag

 

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your email'
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Choose a username'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter password'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Confirm password'
    }))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class ProfileForm(forms.ModelForm):
 class Meta:
    model = Profile
    fields = [ 'profile_picture', 'bio']
    widgets = {
    'bio': forms.Textarea(attrs={
    'class': 'mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm h-32 p-4'
    }),
    }

class PhotoForm(forms.ModelForm):
  tags = forms.CharField(
        required=False,
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'Enter tags separated by commas'}),
        label='Tags (comma separated)'
    )

  class Meta:
        model = Photo
        fields = ['title', 'description','uploaded_photo', 'tags']  

  def save(self, *args, **kwargs):
        photo = super().save(commit=False)
        photo.save()

        tags_input = self.cleaned_data.get('tags')
        if tags_input:
            tag_names = [tag.strip() for tag in tags_input.split(',')]
            for name in tag_names:
                tag, created = Tag.objects.get_or_create(name=name)
                photo.tags.add(tag)

        return photo

gallery_app/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.db.models.signals import post_save
from django.dispatch import receiver
from . models import Subscriber, Profile, Tag, Photo
from . forms import RegistrationForm, ProfileForm, PhotoForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import logout

def home(request):
    tags = Tag.objects.all()

    selected_tag = request.GET.get('tag','')
    if selected_tag:
        tag = Tag.objects.get(name=selected_tag)
        photos = Photo.objects.filter(tags=tag)
    else:
        photos = Photo.objects.all()

    return render(request, 'index.html', {'photos': photos, 'tags': tags})

def register(request):
 if request.method == 'POST':
    form = RegistrationForm(request.POST)
    if form.is_valid():
        form.save()
    return redirect('login')
 else:
    form = RegistrationForm()
 return render(request, 'registration/register.html', {'form': form})


def custom_logout(request):
    if request.method == 'POST':
        logout(request)
        return redirect('logout')  
    return redirect('/') 

@login_required
def subscribe(request):
    if request.method == 'POST':
        email= request.POST['email']
        if Subscriber.objects.filter(email=email).exists():
            messages.error(request, 'You are already subscribed.')
        else:
            subscriber = Subscriber(email=email)
            subscriber.save()
            messages.success(request, 'Thank you for subscribing!')
            return redirect('subscribe')
    return render(request, 'subscribe.html')

@login_required
def profile_view(request):
    return render(request, 'profile.html', {'profile': request.user.profile})


@login_required
@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

@login_required
def edit_profile(request):
    profile = request.user.profile
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('profile')  
    else:
        form = ProfileForm(instance=profile)
    return render(request, 'edit_profile.html', {'form': form})

@login_required
def photo_upload(request):
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = PhotoForm()

    return render(request, 'add_photo.html', {'form': form})


def filter_photos(request):
    tags_param = request.GET.get('tags', '')  

    tag_names = tags_param.split(',')

    tags = Tag.objects.filter(name__in=tag_names)

    photos = Photo.objects.filter(tags__in=tags).distinct()

    return render(request, 'index.html', {'photos': photos})

@login_required
def like_photo(request, photo_id):
    photo = get_object_or_404(Photo, id=photo_id)
    photo.total_likes += 1
    photo.save()
    return redirect(request.META.get('HTTP_REFERER', 'index'))

@login_required
def dislike_photo(request, photo_id):
    photo = get_object_or_404(Photo, id=photo_id)
    photo.total_dislikes += 1
    photo.save()
    return redirect(request.META.get('HTTP_REFERER', 'index'))

def photo_detail(request, photo_id):
    photo = get_object_or_404(Photo, id=photo_id)
    return render(request, 'photo_detail.html', {'photo': photo})
# Create your views here.

gallery_app/templates/add_photo.html
{% extends 'base.html' %}

{% block title %}Photo Gallery | Add Photo{% endblock %}

{% block body %}
<div class="py-4 mt-auto">
    <div class="container px-4">
        <div class="d-flex justify-content-center">
            <h3>Add Photo</h3>
        </div>

        {% if messages %}
            {% for message in messages %}
                <div class="text-center text-danger pt-1 pb-2">{{ message }}</div>
            {% endfor %}
        {% endif %}

        <div class="row">
            <div class="col-lg-6 offset-lg-3">
                <div class="card bg-light mb-3">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="id_title" class="form-label mt-4">Title</label>
                                <input type="text" name="title" id="id_title" placeholder="Enter photo title"
                                       class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label for="id_description" class="form-label mt-4">Description</label>
                                <textarea name="description" id="id_description" rows="4"
                                          placeholder="Enter photo description" class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <label for="id_tags" class="form-label mt-4">Tags (comma separated)</label>
                                <input type="text" name="tags" id="id_tags" placeholder="Enter tags separated by commas"
                                       class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label for="id_uploaded_photo" class="form-label mt-4">Upload Photo</label>
                                <input type="file" name="uploaded_photo" id="id_uploaded_photo" class="form-control" required>
                            </div>

                            <div class="form-group mt-4">
                                <button type="submit" class="btn btn-primary">
                                    Add Photo
                                </button>
                            </div>
                        </form>

                        <div class="mt-2">
                            <a href="{% url 'index' %}" class="btn btn-link">Back to Gallery</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

gallery_app/templates/add_profile.html
{% extends 'base.html' %} {% block title %}Add Profile {% endblock %}
{% block body%}
<form method="post" class="max-w-lg mx-auto mt-8 mb-8 shadow-lg p-4 ">
  {% csrf_token %}
  <div class="mb-4">
    <label
      for="{{ form.content.id_for_label }}"
      class="block text-gray-700 font-bold mb-2"
      >Bio:</label
    >
    {{ form.bio }}
  </div>
  <div class="mb-4">
    <label
      for="{{ form.image.id_for_label }}"
      class="block text-gray-700 font-bold mb-2"
      >Image:</label
    >
    {{ form.profile_picture }}
  </div>

  <button
    type="submit"
    class="btn btn-primary"
  >
    Save
  </button>
</form>
{% endblock %}

gallery_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang='en'>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='icon' type='image/x-icon' href='{% static "images/favicon.ico" %}'>
        <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css' rel='stylesheet'>
        <link href='https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap' rel='stylesheet'>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <title>{% block title %}Photo Gallery{% endblock %}</title>
    </head>

    <body>

        <nav class='navbar navbar-expand-lg navbar-light shadow'>
            <div class='container-fluid'>
                <a class='navbar-brand'>
                     Photo Gallery
                </a>
                <button class='navbar-toggler' type='button' data-bs-toggle='collapse' data-bs-target='#navbarColor' aria-controls='navbarColor' aria-expanded='false' aria-label='Toggle navigation'>
                    <span class='navbar-toggler-icon'></span>
                </button>
                
                <div class='collapse navbar-collapse col-md-6' id='navbarColor'>
                    <ul class='navbar-nav me-auto'>
                        <li class='nav-item'>
                            <a class="nav-link" href="{% url 'index' %}">
                                 Home
                            </a>
                        </li>
                        <li class='nav-item'>
                            <a class='nav-link' href="/upload">
                                Add Photo
                            </a>
                        </li>

                        
                         <li class='nav-item'>
                            <a class='nav-link' href="/subscribe">
                                Subscribe
                            </a>
                        </li>


                        
                    </ul>

                    <ul class='navbar-nav ms-auto'>
                        {% if user.is_authenticated %}

                        <li class='nav-item dropdown'>
                            <a class='nav-link dropdown-toggle' data-bs-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>
                                <i class='fas fa-user fa-fw fa-lg'></i>
                            </a>
                            <div class='dropdown-menu dropdown-menu-end'>
                                <a class='dropdown-item' href="{% url 'profile' %}">
                                    <i class='fas fa-user'></i> User Profile
                                </a>
                                <div class='dropdown-divider'></div>
                                
                                <a class='dropdown-item' href="{% url 'logout' %}">
                                    <form method="POST" action="{% url 'logout' %}">
                                        {% csrf_token %}
                                        <button type="submit"><i class='fas fa-sign-out-alt'></i>Log Out</button>
                                    </form>
                                    
                                </a>
                            </div>
                        </li>
                        {%else%}
                        <li class='nav-item'>
                            <a class='nav-link' href="{% url 'login' %}">
                                <i class='fas fa-sign-in-alt'></i> Log In
                            </a>
                        </li>
                        
                        <li class='nav-item'>
                            <a class='nav-link' href="{% url 'register' %}">
                                <i class='fas fa-user-plus'></i> Register
                            </a>
                        </li>
                        {% endif %}

                        
                    </ul>
                </div>
            </div>
        </nav>

        <main>
            <div class='container'>
                {% block body %}
                {% endblock %}
            </div>
        </main>

        <footer class='py-4'>
            <div class='d-flex align-items-center justify-content-center'>
                <div class='text-center'>
                    Copyright &copy; 2024 Sage Waweru.
                </div>
            </div>
        </footer>

        {% block script %}
        <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js'></script>
        {% endblock %}

    </body>
</html>

gallery_app/templates/edit_profile.html
{% extends 'base.html' %}

{% block body %}
<div class="container mt-4">
    <div class="d-flex justify-content-center">
        <h3>Edit Profile</h3>
    </div>
    
    <div class='row'>
        <div class='col-lg-6 offset-lg-3'>
            <div class='card bg-light mb-3'>
                <div class='card-body'>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                        <div class='form-group'>
                            <label for="id_bio" class='form-label mt-4'>Bio:</label>
                            <textarea name="bio" id="id_bio" class="form-control">{{ form.bio.value }}</textarea>
                        </div>
                        
                        <div class='form-group'>
                            <label for="id_profile_picture" class='form-label mt-4'>Profile Picture:</label>
                            <input type="file" name="profile_picture" id="id_profile_picture" class="form-control">
                        </div>
                                                
                        <div class='form-group mt-4 d-flex '>
                            <button type="submit" class="btn btn-primary mr-2">Save Changes</button>
                            <a href="{% url 'profile' %}" class="btn btn-danger">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

gallery_app/templates/index.html
{% extends "base.html" %}

{% block body %}
{% if user.is_authenticated %}
<h2 class="mt-4">Welcome, {{user.username}}</h2>
{% endif %}
<form method="get" action="{% url 'index' %}" class="mb-4 mt-4">
    <label for="tag" style="font-size: 1.3rem;">Filter by Tag: </label>
    <select name="tag" id="tag" class="w-25 text-center" style="height: 2.3rem;">
      <option value="">--All Tags--</option>
      {% for tag in tags %}
        <option value="{{ tag.name }}" {% if request.GET.tag == tag.name %}selected{% endif %}>{{ tag.name }}</option>
      {% endfor %}
    </select>
    <button type="submit" style="width: 6rem;" class="btn btn-primary">Filter</button>
  </form>
    
  <div class="container py-3">
    <div class="row gy-3 ">
        {% for photo in photos %}
        <div class="col-12 col-sm-6 col-lg-4 mb-4">
            <div style="width: 350px; height: 450px;" class="card shadow">
                <img src="{{ photo.uploaded_photo.url }}" alt="{{ photo.title }}" style="width: 350px; height: 200px;" class="card-img-top img-fluid">
                <div class="card-body">
                    <h5 class="card-title">{{ photo.title }}</h5>
                    <p class="card-text text-muted">
                        {% for tag in photo.tags.all %}
                        {{ tag.name }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </p>
                    <div class="d-flex ">
                        <form action="{% url 'like_photo' photo.id %}" method="post" class="me-3">
                            {% csrf_token %}
                            <button class="btn b btn-sm" data-id="{{ photo.id }}">❤</button>
                        </form>
                        <span id="like-count-{{ photo.id }}" class="me-3">{{ photo.total_likes }} Likes</span>

                        <form action="{% url 'dislike_photo' photo.id %}" method="post" class="me-3">
                            {% csrf_token %}
                            <button class="btn btn-sm" data-id="{{ photo.id }}">❌</button>
                        </form>
                        <span id="dislike-count-{{ photo.id }}">{{ photo.total_dislikes }} Dislikes</span>
                    </div>
                    <div class="mt-3">
                        <a href="{% url 'photo_detail' photo.id %}" class="btn btn-link">Learn More ⏩</a>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <p>No photos available for this tag.</p>
        {% endfor %}
    </div>
</div>
    {% endblock %}

gallery_app/templates/photo_detail.html
{% extends "base.html" %}

{% block title %}Photo Detail{% endblock %}

{% block body %}
<div class="container mt-4">
    <h1 class="mb-4">{{ photo.title }}</h1>
    <img src="{{ photo.uploaded_photo.url }}" alt="{{ photo.title }}" class="img-fluid mb-4" style="max-width: 100%; height: auto;">
    <p class="mb-3">{{ photo.description }}</p>

    <h4 class="mb-4">
        <strong>Tags:</strong>
        {% for tag in photo.tags.all %}
            <span class="badge bg-secondary">{{ tag.name }}</span>
        {% endfor %}
    </h4>

    <div class="d-flex align-items-center mb-4">
        <form action="{% url 'like_photo' photo.id %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn mr-2 ">❤ </button>
        </form>
        <span class="ms-2 me-4">{{ photo.total_likes }} Likes</span>

        <form action="{% url 'dislike_photo' photo.id %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn  mr-2">❌ </button>
        </form>
        <span class="ms-2">{{ photo.total_dislikes }} Dislikes</span>
    </div>

    <a href="{% url 'index' %}" class="btn btn-primary">Back to Gallery</a>
</div>
{% endblock %}

gallery_app/templates/profile.html
{% extends "base.html" %}

{% block body %}

<div class='card  mb-3 w-50 shadow-lg mt-4 mx-auto'>
    <div class='card-header'>
        {% if profile.profile_picture %}
        <img src="{{ profile.profile_picture.url }}" alt="Profile Picture" class="img-fluid rounded-circle" style="width: 150px; height: 150px;">
      {% else %}
        <img src="https://via.placeholder.com/150" alt="Profile Picture" class="img-fluid rounded-circle" style="width: 150px; height: 150px;">
      {% endif %}     
     <h4><strong>{{ user.username }}</strong>         
     <a href="{% url 'edit_profile' %}"><i class='fas fa-edit'></i></a>
     </h4>
    

    </div>
    <div class='card-body'>
        <div class='d-flex w-100 justify-content-between mb-2'>
            {% if profile.bio %}
            <p><strong>Bio:</strong> {{ profile.bio }}</p>
          {% else %}
          <p><strong>Bio:</strong> No bio available.</p>
          {% endif %}
    
        </div>
        <div class='d-flex w-100 justify-content-between mb-2'>
            <p class='mb-1'>
                <strong>Email:</strong> {{ user.email }}
            </p>
        </div>
        <div class='d-flex w-100 justify-content-between mb-2'>
            <p class='mb-1'>
                <strong>Date joined:</strong> {{ user.date_joined }}
            </p>
        </div>

        <div class='d-flex w-100 justify-content-between mb-2'>
            <p class='mb-1'>
                <strong>Last login:</strong> {{ user.last_login }}
            </p>
        </div>
    </div>
</div>

{% endblock %}

gallery_app/templates/subscribe.html
{% extends 'base.html' %}
{% block body %}
<div class="container py-5">
  <h2 class="text-center mb-4">
    Subscribe to our newsletter
  </h2>
  {% if messages %}
  <div class="mb-4">
    {% for message in messages %}
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
  </div>
  {% endif %}
  <form method="post" action="{% url 'subscribe' %}">
    {% csrf_token %}
    <div class="mb-3">
      <label for="email" class="form-label">Email address</label>
      <input
        type="email"
        id="email"
        name="email"
        required
        class="form-control"
      />
    </div>
    <button type="submit" class="btn btn-primary w-100">
      Subscribe
    </button>
  </form>
</div>
{% endblock %}